FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY manifest.json /usr/share/nginx/html/manifest.json
COPY sw.js /usr/share/nginx/html/sw.js
COPY shared /usr/share/nginx/html/shared

EXPOSE 80
